name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Auto assign
      uses: kentaro-m/auto-assign-action@v1.2.6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: '.github/auto_assign.yml'
